"""Segmentation metrics — all computed on REAL held-out data.

  - iou / dice            : standard overlap metrics
  - relaxed_iou           : Length-Complete / Relaxed IoU with a tolerance buffer (px),
                            so minor alignment shifts are not penalised
  - occlusion_recall      : recall of road pixels INSIDE a controlled occluded region —
                            directly measures the occlusion-robustness claim. The occlusion
                            mask is generated by us at eval time (a controlled perturbation
                            of real images), so we know exactly which pixels were hidden.
"""
import numpy as np
import torch
import cv2


@torch.no_grad()
def binarize(logits, thr=0.5):
    return (torch.sigmoid(logits) > thr).float()


@torch.no_grad()
def iou_dice(pred, target, eps=1e-6):
    p = pred.reshape(-1)
    t = target.reshape(-1)
    inter = (p * t).sum()
    union = p.sum() + t.sum() - inter
    iou = ((inter + eps) / (union + eps)).item()
    dice = ((2 * inter + eps) / (p.sum() + t.sum() + eps)).item()
    return iou, dice


@torch.no_grad()
def occlusion_recall(pred, target, occ_mask, eps=1e-6):
    """Recall (TP / (TP+FN)) over road pixels that fell inside the occluded region."""
    region = occ_mask
    t = (target * region).reshape(-1)
    p = (pred * region).reshape(-1)
    tp = (p * t).sum()
    fn = ((1 - p) * t).sum()
    return (tp / (tp + fn + eps)).item()


def relaxed_iou(pred_np, target_np, buffer_px=3, eps=1e-6):
    """Buffered IoU: a predicted road pixel within `buffer_px` of GT counts as a hit."""
    k = 2 * buffer_px + 1
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (k, k))
    pred_np = pred_np.astype(np.uint8)
    target_np = target_np.astype(np.uint8)
    t_dil = cv2.dilate(target_np, kernel)
    p_dil = cv2.dilate(pred_np, kernel)
    tp = np.logical_and(pred_np, t_dil).sum()
    fp = np.logical_and(pred_np, np.logical_not(t_dil)).sum()
    fn = np.logical_and(target_np, np.logical_not(p_dil)).sum()
    return float((tp + eps) / (tp + fp + fn + eps))


class RunningMean:
    """Accumulates a metric across batches (weighted by sample count)."""
    def __init__(self):
        self.s = 0.0
        self.n = 0

    def update(self, v, k=1):
        self.s += v * k
        self.n += k

    @property
    def avg(self):
        return self.s / max(self.n, 1)
